# -*- coding: utf-8 -*-
"""machinefailure_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSQS3nDJU2eq8TQ3fysd042gAeLODPuh
"""

import streamlit as st
import joblib
import pandas as pd

model=joblib.load("dtc_model (1).pkl")

st.title("wine type perdiction !")

footfall =st.number_input("footfall")
tempMode=st.number_input("tempMode")
AQ =st.number_input("AQ")
USS	=st.number_input("USS	")
CS=st.number_input("CS")
VOC=st.number_input("VOC")
RP=st.number_input("RP")
IP=st.number_input("IP")
Temperature=st.number_input("Temperature")
fail=st.number_input("fail")

input_data=pd.dataframe({
    "footfall":[footfall],
    "volatile_acidity":[volatile_acidity],
    "AQ":[AQ],
    "USS":[USS],
    "CS":[CS],
    "VOC":[VOC],
    "RP":[RP],
    "IP":[IP],
    "Temperature":[Temperature],
    "fail":[fail],


})
if st.button("predict"):
    prediction=model.predict(input_data)[0]
    if prediction==0:
        st.success("fail")
    else:
        st.error("not fail")
